Vagrant.configure("2") do |config|

  ## node 1 
  config.vm.define "tnode01" do |nodedeb1|
    nodedeb1.vm.box = "ubuntu/trusty64"
    nodedeb1.vm.hostname = "tnode01"
    nodedeb1.vm.network :private_network,
                        :ip => "192.168.222.201"
    nodedeb1.ssh.insert_key = false

    ## Shell script provisionning
    nodedeb1.vm.provision "shell" do |shell|
      shell.path = "vagrant/bootstrap.sh"
      shell.args = "192.168.222.1 eth1"
    end

    nodedeb1.vm.provider "virtualbox" do |v|
         v.memory = 1024
         v.cpus = 1
		 v.name = "tnode01"
    end
  end


  ##  node 2
  config.vm.define "tnode02" do |nodedeb2|
    nodedeb2.vm.box = "ubuntu/trusty64"
    nodedeb2.vm.hostname = "tnode02"
    nodedeb2.vm.network :private_network,
                        :ip => "192.168.222.202"
    nodedeb2.ssh.insert_key = false

    ## Shell script provisionning
    nodedeb2.vm.provision "shell" do |shell|
      shell.path = "vagrant/bootstrap.sh"
      shell.args = "192.168.222.1 eth1"
    end

    nodedeb2.vm.provider "virtualbox" do |v|
         v.memory = 1024
         v.cpus = 1
		 v.name = "tnode02"
    end
  end

# will add provisioning here
  ## synced folder configuration
  config.vm.synced_folder "vagrant", "/vagrant", type: "rsync"

end
