Vagrant.configure("2") do |config|

  ## node 1 
  config.vm.define "node01" do |nodedeb1|
    nodedeb1.vm.box = "debian/jessie64"
    nodedeb1.vm.hostname = "node01"
    nodedeb1.vm.network :private_network,
                        :ip => "192.168.122.201"

    ## Shell script provisionning
    nodedeb1.vm.provision "shell" do |shell|
      shell.path = "vagrant/bootstrap.sh"
      shell.args = "192.168.122.1 eth1"
    end

    nodedeb1.vm.provider "virtualbox" do |v|
         v.memory = 1024
         v.cpus = 1
		 v.name = "node01"
    end
  end


  ##  node 2
  config.vm.define "node02" do |nodedeb2|
    nodedeb2.vm.box = "debian/jessie64"
    nodedeb2.vm.hostname = "node02"
    nodedeb2.vm.network :private_network,
                        :ip => "192.168.122.202"

    ## Shell script provisionning
    nodedeb2.vm.provision "shell" do |shell|
      shell.path = "vagrant/bootstrap.sh"
      shell.args = "192.168.122.1 eth1"
    end

    nodedeb2.vm.provider "virtualbox" do |v|
         v.memory = 1024
         v.cpus = 1
		 v.name = "node02"
    end
  end

# will add provisioning here
  ## synced folder configuration
  config.vm.synced_folder "vagrant", "/vagrant", type: "rsync"

end
