Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.33.61"
  config.vm.synced_folder ".", "/vagrant"

  # Provisioning configuration for Ansible.
    config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
